#ifndef ERROR_H
#define ERROR_H

#include <glad/glad.h>

// Executed whenever a debug message is generated by OpenGL, including the critical errors.
void APIENTRY debugMessageCallback(
  GLenum source,
  GLenum type,
  GLuint id,
  GLenum severity,
  GLsizei length,
  const GLchar *message,
  const void *userParam);

#endif  // ERROR_H
